/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Model.Endereco;
import Model.Fabricante;
import Model.Produto;
import Model.Usuario;
import Model.Compra;

public class JFprincipal extends javax.swing.JFrame {

    public static Produto produto = new Produto();
    public static Endereco endereco = new Endereco();
    public static Fabricante fabricante;
    public static Usuario usuario = new Usuario();
    public static Compra venda = new Compra();
    
    public static boolean cadastro = false;

    public JFprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenuItem();
        jMenuFabricante = new javax.swing.JMenuItem();
        jMenuEndereço = new javax.swing.JMenuItem();
        jMenuRealizarUmaCompra = new javax.swing.JMenu();
        jMenuItemComprar = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuConsultarUsuario = new javax.swing.JMenuItem();
        jMenuConsultarProdutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Castrado de Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jMenuCadastrar.setText("Cadastrar");

        jMenuUsuario.setText("Usuario");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuUsuario);

        jMenuProduto.setText("Produto");
        jMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuProduto);

        jMenuFabricante.setText("Fabricante");
        jMenuFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFabricanteActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuFabricante);

        jMenuEndereço.setText("Endereço");
        jMenuEndereço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEndereçoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuEndereço);

        jMenuBar1.add(jMenuCadastrar);

        jMenuRealizarUmaCompra.setText("Comprar");

        jMenuItemComprar.setText("Realizar Uma compra");
        jMenuItemComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComprarActionPerformed(evt);
            }
        });
        jMenuRealizarUmaCompra.add(jMenuItemComprar);

        jMenuBar1.add(jMenuRealizarUmaCompra);

        jMenuConsultar.setText("Consultar");
        jMenuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarActionPerformed(evt);
            }
        });

        jMenuConsultarUsuario.setText("Usuário");
        jMenuConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarUsuarioActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuConsultarUsuario);

        jMenuConsultarProdutos.setText("Produtos");
        jMenuConsultarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarProdutosActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuConsultarProdutos);

        jMenuBar1.add(jMenuConsultar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
        JFprincipal.cadastro = false;

    }//GEN-LAST:event_formWindowOpened

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed

        if (cadastro == false) {
            JifCadastroUsuario obj = new JifCadastroUsuario();
            jDesktopPanePrincipal.add(obj);
            obj.setVisible(true);
        }


    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutoActionPerformed
        if (cadastro == false) {
            JifCadastroProduto obj = new JifCadastroProduto();
            jDesktopPanePrincipal.add(obj);
            obj.setVisible(true);
        }

    }//GEN-LAST:event_jMenuProdutoActionPerformed

    private void jMenuEndereçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEndereçoActionPerformed
        if (cadastro == false) {
            JifCadastroEndereço obj = new JifCadastroEndereço();
            jDesktopPanePrincipal.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jMenuEndereçoActionPerformed

    private void jMenuFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFabricanteActionPerformed
        if (cadastro == false) {
            JifCadastroFabricante obj = new JifCadastroFabricante();
            jDesktopPanePrincipal.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jMenuFabricanteActionPerformed

    private void jMenuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarActionPerformed


    }//GEN-LAST:event_jMenuConsultarActionPerformed

    private void jMenuConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarUsuarioActionPerformed
        if (cadastro == false) {
            JifConsultaUsuario obj = new JifConsultaUsuario();
            jDesktopPanePrincipal.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jMenuConsultarUsuarioActionPerformed

    private void jMenuConsultarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarProdutosActionPerformed
        if (cadastro == false) {
            JifConsultaProduto obj = new JifConsultaProduto();
            jDesktopPanePrincipal.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jMenuConsultarProdutosActionPerformed

    private void jMenuItemComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComprarActionPerformed
        if (cadastro == false) {
            JifRealizarUmaCompra obj = new JifRealizarUmaCompra();
            jDesktopPanePrincipal.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuItem jMenuConsultarProdutos;
    private javax.swing.JMenuItem jMenuConsultarUsuario;
    private javax.swing.JMenuItem jMenuEndereço;
    private javax.swing.JMenuItem jMenuFabricante;
    private javax.swing.JMenuItem jMenuItemComprar;
    private javax.swing.JMenuItem jMenuProduto;
    private javax.swing.JMenu jMenuRealizarUmaCompra;
    private javax.swing.JMenuItem jMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
